import type { UserInfoInput } from "./types"

export const localStrings = {
    GREET_MEET_YOUR_SHAPELY_PROVIDER: "Great! Let's get you scheduled to meet with your Shapely provider!",
    WHAT_TIME_WORKS_BEST: "What time works best for your video session?",
    SELECT_DATE_TIME: "Select Date and Time",
    TIMEZONE: "Timezone:",
    MORNING: "Morning",
    AFTERNOON: "Afternoon",
    EVENING: "Evening",
    NO_AVAILABLE_SLOTS: "No available time slots",
    SELECT_ANOTHER_DATE: "Select another date or try other options:",
    GO_TO_NEXT_AVAILABILITY: "Go to next availability",
    CONFIRM_DATE_TIME: "Confirm Date and Time",
    CONFIRM_YOUR_INFO: "Awesome! Let's confirm your information to complete your sign-up",
    APPOINTMENT: "Appointment",
    YOUR_INFO: "Your Information",
    FIRST_NAME: "First Name",
    LAST_NAME: "Last Name",
    EMAIL: "Email",
    PHONE_NUMBER: "Phone Number",
    PAYMENT_INFO: "Payment Information",
    CARD_NUMBER: "Card number",
    EXPIRY_DATE: "Expiry Date",
    SIGN_UP: "Sign Up",
    POWERED_BY: "Powered by",
    STRIPE: "Stripe",
    TERMS: "Terms",
    PRIVACY: "Privacy",
    MEMBERSHIP: "Your Shapely Membership",
    JUST_ONE_MONTH: "Just $49 for the first month -",
    THEN_99_MONTH: "then $99/month",
    MEMBERSHIP_BENEFITS: ["Monthly video visits with provider", "Affordable access to weight loss medications", "App and provide chat"],
    ANY_QUESTIONS: "Any questions?",
    HERE_TO_HELP: "We're here to help!",
    CALL_US: "Call us at :",
    NUMBER: "(424) 600-8360",
    EMAIL_US_AT: "Email us at :",
    EMAIL_ID: "hello@getshapely.com",
    EXCITED_TO_MEET: `You're all set! We're excited to meet you for your first visit!\n Here are next steps:`,
    STEPS: (date: string) => [
        {
            HEADING: "Sign in to your Healthie account",
            SUBHEADING: "with the email you just received. We use Healthie as our secure patient portal."
        },
        {
            HEADING: "Complete the questionnaire and consent forms before your first visit.",
            SUBHEADING: "This will allow for a smooth and easy visit with your Shapely provider."
        },
        {
            HEADING: "Get ready for your video visit!",
            LIST: [`Your appointment is scheduled for ${date}`, "You'll receive a secure video link via email to join your video visit. Please join 5 minutes early to ensure everything is working properly."]
        },
    ],
    SELECT_APPOINTMENT_TYPE: "Select Appointment Type",
    TOP_NUTRITION_GOALS: "What are your top nutrition goals?",
    USE_TO_FIND_MATCH: "We'll use this to find your perfect match",
    SELECT_THAT_APPLY: "Select all that apply",
    CONTINUE: "Continue",
    NUTRITION_GOAL_URL: "/funnel/nutrition-goals",
    NEXT_STEPS_URL: "/funnel/next-steps",
    CHECK_INSURANCE_BENEFITS: "Let's Check Your Insurance Benefits",
    NEED_SOME_INFO: "We need some info to check your coverage and show you dietitians who are in-network.",
    PATIENTS_HAVE_COVERAGE: "💡 94% of Shapely patients have coverage\n and pay",
    OUT_OF_POCKET: " $0 out of pocket.",
    ALL_INFO_SECURE: "All information you share is secure and confidential",
    WHICH_STATE_LIVE_IN: "What state do you live in?",
    MATCH_WITH_REGISTERED_DIETITIAN_ID: "We'll use this to match you with a registered dietitian licensed in your state.",
    IN_A_GOOD_COMPANY: "You're in good company",
    THOUSANDS_OF_PEOPLE: "Thousands of people just like you have used their insurance to get covered, expert care through Shapely.",
    BENEFITS_LITS: ["Video visits with an expert dietitian", "Matched with dietitians licensed in your state", "Trusted by thousands of patients"],
    INSURANCE_PLAN: "Which insurance plan do you have?",
    ACCEPT_MAJOR_PPO: "We accept most major PPO and Medicare insurances",
    SHAPELY_DIETITIAN: "Let's get you started with a Shapely dietitian",
    GUIDE_THROUGH_NEXT_STEP: "Share your contact details, and we'll guide you through the next steps.",
    CONTINUE_TO_AGREE: "By clicking continue, you agree to our",
    PRIVACY_POLICY: "Privacy Policy",
    AND: "and",
    TERMS_OF_USE: "Terms of Use.",
    USE_SAME_NAME_AS_INSURANCE_PLAN: "Please use the same name that is on your insurance plan.",
    YOUR_BIRTHDAY: "When's your birthday?",
    EIGHTEEN_OLDER: "Currently we only treat patients 18 and older",
    WE_NEED_THIS_INFO: "We need this information to check your insurance benefits",
    ADD_YOUR_INSURANCE_DETAILS: "Add your insurance details",
    SHAPELY_IN_NETWORK_WITH_HEALTH_PLANS: "Shapely is in network with major health plans, and most patients pay $0 out of pocket. We'll run a benefits check to make sure we accept your insurance",
    MEMBER_ID: "Member Id",
    MEMBER_ID_KEY: "member_id",
    TYPE_NUMBER: "number",
    INSURANCE_PLAN_LABEL: "Insurance Plan",
    DOUBLE_CHECK_INFO: "Please double check your information",
    NOT_ABLE_TO_VERIFY: `We weren't able to verify your coverage due to this error: invalid subscriber ID.\n Please review and make sure everything is correct.`,
    DETAILS: [
        {
            label: "First name",
            key: "first_name",
            type: "text",
        },
        {
            label: "Last name",
            key: "last_name",
            type: "text",
        },
        {
            label: "State",
            key: "state",
            type: "text",
        },
        {
            label: "Date of birth",
            key: "dob",
            type: "text",
        },
        {
            label: "Insurance plan",
            key: "insurancePlan",
            type: "text",
        },
        {
            label: "Member ID",
            key: "memberId",
            type: "number",
        }
    ],
    WHICH_FOLLOWING_APPLY: "Which of the following apply to you?",
    CERTAIN_DIAGNOSES: "Medicare only covers a dietitian for people with certain diagnoses.",
    SELF_PAY_PROGRAM: "While Medicare will not cover a nutritionist for your medical conditions, you can access a nutritionist through our self-pay program",
    PAY_JUST_$125: "You'll pay just $125 per 60-minute visit — whether it's your first appointment or a follow-up with your expert dietitian",
    YES_CONTINUE: "Yes, I'd like to continue",
    NO_THANKS: "No thanks, I don't want to continue",
    STILL_COVER_WEIGHT_LOSS_PROGRAM: "Good news — you can still work with a dietitian through our Medicare-covered weight loss program",
    CURRENTLY_NOT_COVERING_NUTRITION: "While Medicare doesn't currently cover nutrition visits for your condition, Shapely offers a physician-led weight loss program that is covered by Medicare.",
    AS_PART_OF_PROGRAM: "As part of this program, you'll receive:",
    BENEFITS_RECEIVE_LIST: ["Regular video visits with a weight loss provider", "Monthly video visits with a dietitian", "Affordable access to weight loss drugs (optional)"],
    YES_INTERESTED: "Yes, I'm interested!",
    WE_CURRENTLY_NOT_IN_NETWORK_WITH_YOUR_INSURANCE: "While we're not currently in-network with your insurance, you can still access expert nutrition care through our affordable self-pay option.",
    YES_LIKE_TO_CONTINUE: "Yes, I'd like to continue",
    THANKS_FOR_INTEREST: "Thanks for your interest in Shapely!",
    CHECK_BACK_SOON: "Please check back soon as we are constantly adding new insurances to Shapely.",
    FEEL_FREE_TO_REACH: "Feel free to reach out at",
    SHAPELY_EMAIL: "hello@getshapely.com",
    FOR_ANY_QUESTION: "for any questions.",
    YOU_COVERED: "🎉 You're Covered!",
    BASED_ON_ANS: "Based on your answers, we've matched you with a dietitian specializing in your goals!",
    MEET_MATCH: "Meet your match",
    BOOK_YOUR_VISIT: "Book your first visit",
    QUESTIONS: "Questions?",
    TALK_TO_COORDINATOR: "Talk to a care coordinator",
    NEED_A_CARD: "We need a card on file to hold your appointment",
    CONFIRM_COVERAGE_BEFORE_APPOINTMENT: "Most patients pay $0, and we'll confirm your coverage before your appointment. We won't charge your card unless you miss your appointment.",
    RISK_FREE_BOOKING_CANCELATION: "Risk-free booking and cancellation (?)",
    YOU_ARE_ALL_SET: "You're all set! We're excited to meet you for your first visit! Here are next steps:",
    SHAPELY_NOT_SERVING_CURRENTLY_IN_YOUR_STATE: "Shapely currently does not serve patients in your state, but we are working to as soon as possible! We will let you know as soon as we serve patients in your state.",
    SHAPELY_NOT_SERVING_CURRENTLY_PATIENTS_UNDER_18: "Shapely currently does not serve patients under age 18. We apologize for any inconvenience",
    MM_YY: "MM/YY",
    CVC: "CVC",
    RATED_5_STAR: "Rated 5 Stars by 97% of Patients",
    ELIGIBLE_TO_JOIN: "Who is eligible to join Shapely?",
    CURRENTLY_SHAPELY_SERVES: "Currently Shapely serves adults age 18 and older in the states of California, Florida, Georgia, North Carolina, New York, South Carolina, Texas, and Washington. We will soon be expanding to all 50 US states!",
    WHAT_DOES_COVER: "What does my insurance cover?",
    IF_YOU_NEED_CANCEL_RESCHEDULE: "If you need to cancel or reschedule your appointment, please do so with at least 24 hour notice to avoid a $50 late cancellation/no show fee",
    STILL_CHECKING:"We're still checking your insurance",
    WAITING_TO_HEAR:"We're just waiting to hear from your insurer. We'll contact you with the results in 1-2 business days.Some insurance plans take a little longer to confirm, but we'll keep you updated."
}

export const userInfoInputList: UserInfoInput[] = [
    {
        label: localStrings.FIRST_NAME,
        name: "first_name",
        type: "text"
    },
    {
        label: localStrings.LAST_NAME,
        name: "last_name",
        type: "text"
    },
    {
        label: localStrings.EMAIL,
        name: "email",
        type: "email"
    },
    {
        label: localStrings.PHONE_NUMBER,
        name: "phone_number",
        type: "tel",
        inputMode: "numeric", // allows "+" and digits
    },
];