export const stateToTimeZone:any = {
    "Alaska": "America/Anchorage",
    "Alabama": "America/Chicago",
    "Arkansas": "America/Chicago",
    "Arizona": "America/Phoenix",
    "California": "America/Los_Angeles",
    "Colorado": "America/Denver",
    "Connecticut": "America/New_York",
    "District of Columbia": "America/New_York",
    "Delaware": "America/New_York",
    "Florida": "America/New_York",
    "Georgia": "America/New_York",
    "Hawaii": "Pacific/Honolulu",
    "Iowa": "America/Chicago",
    "Idaho": "America/Boise",
    "Illinois": "America/Chicago",
    "Indiana": "America/Indiana/Indianapolis",
    "Kansas": "America/Chicago",
    "Kentucky": "America/Kentucky/Louisville",
    "Louisiana": "America/Chicago",
    "Massachusetts": "America/New_York",
    "Maryland": "America/New_York",
    "Maine": "America/New_York",
    "Michigan": "America/Detroit",
    "Minnesota": "America/Chicago",
    "Missouri": "America/Chicago",
    "Mississippi": "America/Chicago",
    "Montana": "America/Denver",
    "North Carolina": "America/New_York",
    "North Dakota": "America/Chicago",
    "Nebraska": "America/Chicago",
    "New Hampshire": "America/New_York",
    "New Jersey": "America/New_York",
    "New Mexico": "America/Denver",
    "Nevada": "America/Los_Angeles",
    "New York": "America/New_York",
    "Ohio": "America/New_York",
    "Oklahoma": "America/Chicago",
    "Oregon": "America/Los_Angeles",
    "Pennsylvania": "America/New_York",
    "Rhode Island": "America/New_York",
    "South Carolina": "America/New_York",
    "South Dakota": "America/Chicago",
    "Tennessee": "America/Chicago",
    "Texas": "America/Chicago",
    "Utah": "America/Denver",
    "Virginia": "America/New_York",
    "Vermont": "America/New_York",
    "Washington": "America/Los_Angeles",
    "Wisconsin": "America/Chicago",
    "West Virginia": "America/New_York",
    "Wyoming": "America/Denver",
    "chandigarh": "Asia/Kolkata"
  };
  